[project]
name = "pyleetcode"
authors = [{name = "Niakr1s", email = "pavel2188@gmail.com"}]
version = "0.1.0"
requires-python = ">=3.11"
dependencies = []

[project.optional-dependencies]
dev = [
    "pytest"
]
